version: '3.8'

services:
  db:
    image: mariadb:10.4.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: acl
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3310:3310"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80" # Change port as needed
    depends_on:
      - db
      - redis
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
