// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using SharedKernel.Main.IMT.Infrastructure.Persistence.Context.New;

namespace Notification.App.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240708080344_Init_Migration_For_Imt")]
    partial class Init_Migration_For_Imt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("App.Models.IMT.ImtBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("DisplayName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Logo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("logo")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Url")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("url")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_banks", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<int?>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("country_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_cities", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("IsoCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("iso_code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_countries", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("IsoCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("iso_code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Symbol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("symbol")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_currencies", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address1")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Address2")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address2")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("category")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("1=verified, 2=not verified, 3=verified+");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(20)")
                        .HasColumnName("customer_number")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("Dob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("dob")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("FirstName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("LastName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Password")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("1=approved,2= not approvec, 3=active, 4=inactive, 5=suspended, 6=banned etc");

                    b.Property<string>("Tckn")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tckn")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("tckn is government national id");

                    b.Property<sbyte?>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("1=individual, 2=corporate etc");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_customers", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtCustomerBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_no")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("AccountTitle")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_title")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("bank_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("BranchIban")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("branch_iban")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("city_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("country_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("customer_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("can't delete if already exist");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_customer_banks", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtMoneyTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("CommissionPaidBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("commission_paid_by")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("ExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("exchange_rate")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("ExchangedAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("exchanged_amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("Fee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("fee")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("invoice_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("order_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("payment_method_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("ReasonCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("reason_code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("reason_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("ReceiveAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("receive_amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ReceiverCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("receiver_currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ReceiverCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("receiver_customer_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("ReceiverName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("receiver_name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("RemoteOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("remote_order_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("SendAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("send_amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("SenderCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("sender_currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("SenderCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("sender_customer_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("SenderName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sender_name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Source")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("TransactionStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("transaction_state_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("TransferType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("transfer_type")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("1=instant, 2=regular, 3=same_day etc.");

                    b.Property<sbyte?>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("type 1 = b2b, 2 = c2c, 3=c2b, 4=b2c etc");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("Vat")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("vat")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_money_transfers", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtPaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("MethodName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("method_name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("must be soft delete, possible entries=> wallet, debit card, credit card etc");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_payment_methods", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("api_key")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("api key and secret must be encrypted");

                    b.Property<string>("ApiSecret")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("api_secret")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("BaseUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("base_url")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_providers", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtProviderCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("FromCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("from_currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("provider_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("ReceiverCommissionFixed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("receiver_commission_fixed")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("ReceiverCommissionPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("receiver_commission_percentage")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("SenderCommissionFixed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("sender_commission_fixed")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("SenderCommissionPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("sender_commission_percentage")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ToCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("to_currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_provider_commissions", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtProviderErrorDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("ErrorCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("error_code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("ErrorMessage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("error_message")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("ImtProviderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_provider_id");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int(11)")
                        .HasColumnName("reference_id")
                        .HasComment("type-reference table primary key id");

                    b.Property<sbyte>("Type")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("type")
                        .HasComment("1: quotation,2: money_transfer");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_provider_error_details", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtProviderPayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("ImtCountryId")
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_country_id");

                    b.Property<int>("ImtCurrencyId")
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_currency_id");

                    b.Property<int>("ImtProviderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_provider_id");

                    b.Property<int?>("ImtProviderServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_provider_service_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("Increment")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("increment")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("still not clear, asked client");

                    b.Property<sbyte?>("Precision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("precision")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("for declaring precision point after decimal");

                    b.Property<int?>("RemotePayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("remote_payer_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_provider_payers", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtProviderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("ImtProviderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_provider_id");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("BankAccount, WalletTransfer etc");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_provider_services", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtQuotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("DestinationAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("destination_amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ImtDestinationCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_destination_currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ImtProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_provider_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ImtProviderServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_provider_service_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ImtSourceCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_source_country_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("ImtSourceCurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("imt_source_currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode")
                        .HasComment("DESTINATION_AMOUNT, SOURCE_AMOUNT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("order_id");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payer_id");

                    b.Property<decimal?>("SourceAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("source_amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("transaction_type")
                        .HasComment("B2B,B2C,C2C,C2B");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_quotations", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'0'")
                        .HasComment("default value 0 means \"Others\"");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_reasons", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("current_balance")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("customer_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("Fee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("fee")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("Gross")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("gross")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("MoneyFlow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("money_flow")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("1 for incoming, 2 for outgoing");

                    b.Property<string>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("PreviousBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("previous_balance")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("send money request, send money approved, etc");

                    b.Property<int?>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("transaction_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("TransactionStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("transaction_state_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("TransactionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("transaction_type")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("transaction_type = 1 for send, 2 for receive");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_transactions", null, t =>
                        {
                            t.HasComment("transaction_type = 1,2,3; 1= send money, 2=receive money etc.transaction_id is sender table id.money_flow = 1/2; 1= incoming and 2 = outgoing, event_type = send money request, send money approved, send money rejected etc.");
                        });
                });

            modelBuilder.Entity("App.Models.IMT.ImtTransactionLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("currency_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("DailyTotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("daily_total_amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("DailyTotalNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("daily_total_number")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal?>("MonthlyTotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(16, 4)
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("monthly_total_amount")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("MonthlyTotalNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("monthly_total_number")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("TransactionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("transaction_type")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("UserCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("user_category")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_transaction_limits", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtTransactionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("1=completed, 2=pending, 3=approved, 4=");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_transaction_states", (string)null);
                });

            modelBuilder.Entity("App.Models.IMT.ImtTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("created_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'NULL'")
                        .HasComment("send money, receive money, withdrawal etc");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int?>("UpdatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("updated_by_id")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("imt_transaction_types", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
